"""Add unidad_venta and fecha_actualizacion to Producto

Revision ID: d8c99c83efae
Revises: 
Create Date: 2026-03-26 10:46:21.340598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8c99c83efae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_venta', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('pagado_en_linea')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado_en_linea', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('unidad_venta')

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.drop_column('costo_unitario')

    # ### end Alembic commands ###
